In [163]:
# Trader Behaviour & Performance Analysis using Market sentiments 
# Activities
# Data auditing
# Data cleaning
# Data preparation & merging for further analysis

In [92]:
import numpy as np
import pandas as pd

In [93]:
folder_name = "/Users/abhinandho/Desktop/Trader Behaviour & Performance Analytics/data/"

In [94]:
file_name = "fear_greed_index.csv"

In [95]:
df_index = pd.read_csv(folder_name + file_name)

In [96]:
df_index.head()

    timestamp  value classification        date
0  1517463000     30           Fear  2018-02-01
1  1517549400     15   Extreme Fear  2018-02-02
2  1517635800     40           Fear  2018-02-03
3  1517722200     24   Extreme Fear  2018-02-04
4  1517808600     11   Extreme Fear  2018-02-05

In [97]:
df_index['date'] = pd.to_datetime(df_index['date'])

In [98]:
df_index['classification'].unique()

array(['Fear', 'Extreme Fear', 'Neutral', 'Greed', 'Extreme Greed'],
      dtype=object)

In [99]:
df_index['sentiment_binary'] = df_index['classification'].map({
    'Extreme Fear' : 'Fear',
    'Fear' : 'Fear',
    'Greed': 'Greed',
    'Extreme Greed': 'Greed',
    'Neutral':'Neutral'
})

In [100]:
df_index

       timestamp  value classification       date sentiment_binary
0     1517463000     30           Fear 2018-02-01             Fear
1     1517549400     15   Extreme Fear 2018-02-02             Fear
2     1517635800     40           Fear 2018-02-03             Fear
3     1517722200     24   Extreme Fear 2018-02-04             Fear
4     1517808600     11   Extreme Fear 2018-02-05             Fear
...          ...    ...            ...        ...              ...
2639  1745818200     54        Neutral 2025-04-28          Neutral
2640  1745904600     60          Greed 2025-04-29            Greed
2641  1745991000     56          Greed 2025-04-30            Greed
2642  1746077400     53        Neutral 2025-05-01          Neutral
2643  1746163800     67          Greed 2025-05-02            Greed

[2644 rows x 5 columns]

In [101]:
neutral_df = df_index[df_index['classification'] == 'Neutral'][['value']]

In [102]:
neutral_df.head(20)

     value
9       54
20      54
29      47
81      47
83      54
87      52
94      53
166     47
168     46
170     49
171     54
172     53
173     47
174     54
175     54
176     53
177     48
276     48
277     51
278     47

In [103]:
df_index[df_index['sentiment_binary'] == 'Neutral']

       timestamp  value classification       date sentiment_binary
9     1518240600     54        Neutral 2018-02-10          Neutral
20    1519191000     54        Neutral 2018-02-21          Neutral
29    1519968600     47        Neutral 2018-03-02          Neutral
81    1524720600     47        Neutral 2018-04-26          Neutral
83    1524893400     54        Neutral 2018-04-28          Neutral
...          ...    ...            ...        ...              ...
2606  1742967000     47        Neutral 2025-03-26          Neutral
2624  1744522200     45        Neutral 2025-04-13          Neutral
2633  1745299800     47        Neutral 2025-04-22          Neutral
2639  1745818200     54        Neutral 2025-04-28          Neutral
2642  1746077400     53        Neutral 2025-05-01          Neutral

[396 rows x 5 columns]

In [104]:
df_index.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2644 entries, 0 to 2643
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   timestamp         2644 non-null   int64
 1   value             2644 non-null   int64
 2   classification    2644 non-null   object
 3   date              2644 non-null   datetime64[ns]
 4   sentiment_binary  2644 non-null   object
dtypes: datetime64[ns](1), int64(2), object(2)
memory usage: 103.4+ KB

In [105]:
df_index.describe()

          timestamp        value                           date
count  2.644000e+03  2644.000000                           2644
mean   1.631899e+09    46.981089  2021-09-17 11:44:45.022692864
min    1.517463e+09     5.000000            2018-02-01 00:00:00
25%    1.574811e+09    28.000000            2019-11-26 18:00:00
50%    1.631900e+09    46.000000            2021-09-17 12:00:00
75%    1.688989e+09    66.000000            2023-07-10 06:00:00
max    1.746164e+09    95.000000            2025-05-02 00:00:00
std    6.597967e+07    21.827680                            NaN

In [106]:
df_index.head()

    timestamp  value classification       date sentiment_binary
0  1517463000     30           Fear 2018-02-01             Fear
1  1517549400     15   Extreme Fear 2018-02-02             Fear
2  1517635800     40           Fear 2018-02-03             Fear
3  1517722200     24   Extreme Fear 2018-02-04             Fear
4  1517808600     11   Extreme Fear 2018-02-05             Fear

In [107]:
file_name = 'historical_data.csv'

In [108]:
df_hist = pd.read_csv(folder_name + file_name)

In [109]:
df_hist.head()

,Account,Coin,Execution Price,Size Tokens,Size USD,Side,Timestamp IST,Start Position,Direction,Closed PnL,Transaction Hash,Order ID,Crossed,Fee,Trade ID,Timestamp
0,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9769,986.87,7872.16,BUY,02-12-2024 22:50,0.000000,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.345404,8.950000e+14,1.730000e+12
1,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9800,16.00,127.68,BUY,02-12-2024 22:50,986.524596,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.005600,4.430000e+14,1.730000e+12
2,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9855,144.09,1150.63,BUY,02-12-2024 22:50,1002.518996,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.050431,6.600000e+14,1.730000e+12
3,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9874,142.98,1142.04,BUY,02-12-2024 22:50,1146.558564,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.050043,1.080000e+15,1.730000e+12
4,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9894,8.73,69.75,BUY,02-12-2024 22:50,1289.488521,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.003055,1.050000e+15,1.730000e+12

In [110]:
df_hist.describe()

,Execution Price,Size Tokens,Size USD,Start Position,Closed PnL,Order ID,Fee,Trade ID,Timestamp
count,211224.000000,2.112240e+05,2.112240e+05,2.112240e+05,211224.000000,2.112240e+05,211224.000000,2.112240e+05,2.112240e+05
mean,11414.723350,4.623365e+03,5.639451e+03,-2.994625e+04,48.749001,6.965388e+10,1.163967,5.628549e+14,1.737744e+12
std,29447.654868,1.042729e+05,3.657514e+04,6.738074e+05,919.164828,1.835753e+10,6.758854,3.257565e+14,8.689920e+09
min,0.000005,8.740000e-07,0.000000e+00,-1.433463e+07,-117990.104100,1.732711e+08,-1.175712,0.000000e+00,1.680000e+12
25%,4.854700,2.940000e+00,1.937900e+02,-3.762311e+02,0.000000,5.983853e+10,0.016121,2.810000e+14,1.740000e+12
50%,18.280000,3.200000e+01,5.970450e+02,8.472793e+01,0.000000,7.442939e+10,0.089578,5.620000e+14,1.740000e+12
75%,101.580000,1.879025e+02,2.058960e+03,9.337278e+03,5.792797,8.335543e+10,0.393811,8.460000e+14,1.740000e+12
max,109004.000000,1.582244e+07,3.921431e+06,3.050948e+07,135329.090100,9.014923e+10,837.471593,1.130000e+15,1.750000e+12

In [113]:
df_hist.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 211224 entries, 0 to 211223
Data columns (total 8 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   account        211224 non-null  object
 1   coin           211224 non-null  object
 2   size_usd       211224 non-null  float64
 3   side           211224 non-null  object
 4   timestamp_ist  211224 non-null  object
 5   direction      211224 non-null  object
 6   closed_pnl     211224 non-null  float64
 7   fee            211224 non-null  float64
dtypes: float64(3), object(5)
memory usage: 12.9+ MB

In [111]:
# Rename columns to snake_case (professional standard)
df_hist.columns = df_hist.columns.str.strip().str.replace(' ','_').str.lower()

In [112]:
#keeping only useful column droping noise
df_hist = df_hist[['account','coin','size_usd','side','timestamp_ist','direction','closed_pnl','fee']]

In [115]:
df_hist.head()

,account,coin,size_usd,side,timestamp_ist,direction,closed_pnl,fee
0,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7872.16,BUY,02-12-2024 22:50,Buy,0.0,0.345404
1,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,127.68,BUY,02-12-2024 22:50,Buy,0.0,0.005600
2,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,1150.63,BUY,02-12-2024 22:50,Buy,0.0,0.050431
3,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,1142.04,BUY,02-12-2024 22:50,Buy,0.0,0.050043
4,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,69.75,BUY,02-12-2024 22:50,Buy,0.0,0.003055

In [119]:
# convert to datetime first
df_hist['timestamp_ist'] = pd.to_datetime(df_hist['timestamp_ist'], dayfirst=True)

In [120]:
# now extract date
df_hist['date'] = df_hist['timestamp_ist'].dt.normalize()

In [121]:
# Step 3 - check
print(df_hist['direction'].value_counts())
print(df_hist[df_hist['closed_pnl'] != 0].shape[0])

direction
Open Long                    49895
Close Long                   48678
Open Short                   39741
Close Short                  36013
Sell                         19902
Buy                          16716
Spot Dust Conversion           142
Short > Long                    70
Long > Short                    57
Auto-Deleveraging                8
Liquidated Isolated Short        1
Settlement                       1
Name: count, dtype: int64
104408

In [122]:
#keep only rows where actual PnL was realized
df_closed = df_hist[df_hist['closed_pnl']!=0].copy()

In [125]:
df_closed.head()

,account,coin,size_usd,side,timestamp_ist,direction,closed_pnl,fee,timestammp_ist,date
44,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,22156.95,SELL,2024-12-03 14:39:00,Sell,3008.231185,7.754933,2024-12-03 14:39:00,2024-12-03
45,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,226.43,SELL,2024-12-03 14:39:00,Sell,30.741534,0.079248,2024-12-03 14:39:00,2024-12-03
46,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,302.20,SELL,2024-12-03 14:39:00,Sell,40.770089,0.105771,2024-12-03 14:39:00,2024-12-03
47,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,1809.28,SELL,2024-12-03 14:39:00,Sell,243.812267,0.633248,2024-12-03 14:39:00,2024-12-03
48,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,1892.21,SELL,2024-12-03 14:39:00,Sell,254.263735,0.662274,2024-12-03 14:39:00,2024-12-03

In [126]:
print(df_closed.shape)
print(df_closed['direction'].value_counts())

(104408, 10)
direction
Close Long                   48634
Close Short                  35992
Sell                         19646
Short > Long                    69
Long > Short                    57
Auto-Deleveraging                8
Liquidated Isolated Short        1
Settlement                       1
Name: count, dtype: int64

In [128]:
#keeps only voluntary closed trades

keep_directions = ['Close Long','Close Short','Sell']

In [129]:
df_closed = df_closed[df_closed['direction'].isin(keep_directions)].copy()

In [130]:
print(df_closed['direction'].value_counts())

direction
Close Long     48634
Close Short    35992
Sell           19646
Name: count, dtype: int64

In [138]:
# Merge trader data with sentiment data

df_merged = pd.merge(df_closed, df_index[['date','value','classification','sentiment_binary']],
                     on='date',
                     how='inner')

In [139]:
df_merged.head()

,account,coin,size_usd,side,timestamp_ist,direction,closed_pnl,fee,timestammp_ist,date,value,classification,sentiment_binary
0,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,22156.95,SELL,2024-12-03 14:39:00,Sell,3008.231185,7.754933,2024-12-03 14:39:00,2024-12-03,76,Extreme Greed,Greed
1,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,226.43,SELL,2024-12-03 14:39:00,Sell,30.741534,0.079248,2024-12-03 14:39:00,2024-12-03,76,Extreme Greed,Greed
2,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,302.20,SELL,2024-12-03 14:39:00,Sell,40.770089,0.105771,2024-12-03 14:39:00,2024-12-03,76,Extreme Greed,Greed
3,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,1809.28,SELL,2024-12-03 14:39:00,Sell,243.812267,0.633248,2024-12-03 14:39:00,2024-12-03,76,Extreme Greed,Greed
4,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,1892.21,SELL,2024-12-03 14:39:00,Sell,254.263735,0.662274,2024-12-03 14:39:00,2024-12-03,76,Extreme Greed,Greed

In [140]:
df_merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 104266 entries, 0 to 104265
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   account           104266 non-null  object
 1   coin              104266 non-null  object
 2   size_usd          104266 non-null  float64
 3   side              104266 non-null  object
 4   timestamp_ist     104266 non-null  datetime64[ns]
 5   direction         104266 non-null  object
 6   closed_pnl        104266 non-null  float64
 7   fee               104266 non-null  float64
 8   timestammp_ist    104266 non-null  datetime64[ns]
 9   date              104266 non-null  datetime64[ns]
 10  value             104266 non-null  int64
 11  classification    104266 non-null  object
 12  sentiment_binary  104266 non-null  object
dtypes: datetime64[ns](3), float64(3), int64(1), object(6)
memory usage: 10.3+ MB

In [141]:
#drop one timestamp came when merging happened
df_merged = df_merged.drop(columns=['timestammp_ist'])

In [142]:
print(df_merged.shape)
print(df_merged.columns.tolist())

(104266, 12)
['account', 'coin', 'size_usd', 'side', 'timestamp_ist', 'direction', 'closed_pnl', 'fee', 'date', 'value', 'classification', 'sentiment_binary']

In [143]:
print(df_merged[['timestamp_ist', 'date']].head())

        timestamp_ist       date
0 2024-12-03 14:39:00 2024-12-03
1 2024-12-03 14:39:00 2024-12-03
2 2024-12-03 14:39:00 2024-12-03
3 2024-12-03 14:39:00 2024-12-03
4 2024-12-03 14:39:00 2024-12-03

In [148]:
#group by each trader total trades per day

daily = df_merged.groupby(['date','account']).agg(
    daily_pnl = ('closed_pnl','sum'),
    trade_count = ('closed_pnl','count'),
    avg_size_usd = ('size_usd','mean'),
    total_fees = ('fee','sum'),
    win_rate = ('closed_pnl',lambda x : (x > 0).mean()),
    long_ratio = ('side',lambda x : (x.str.upper() =='BUY').mean())
).reset_index()

In [150]:
daily['net_pnl'] = daily['daily_pnl'] - daily['total_fees']

In [151]:
daily = daily.merge(
    df_merged[['date','value','classification','sentiment_binary']].drop_duplicates('date'),
    on = 'date',
    how = 'left'
)

In [154]:
print(daily.shape)

(1690, 12)

In [153]:
print(daily.head())

        date                                     account    daily_pnl  \
0 2023-12-14  0xb1231a4a2dd02f2276fa3c5e2a2f3436e6bfed23  -205.434737
1 2023-12-15  0xb1231a4a2dd02f2276fa3c5e2a2f3436e6bfed23   -24.632034
2 2023-12-17  0xb1231a4a2dd02f2276fa3c5e2a2f3436e6bfed23   304.982785
3 2023-12-19  0xb1231a4a2dd02f2276fa3c5e2a2f3436e6bfed23  1000.538612
4 2023-12-20  0xb1231a4a2dd02f2276fa3c5e2a2f3436e6bfed23   162.732282

   trade_count  avg_size_usd  total_fees  win_rate  long_ratio     net_pnl  \
0            6  12789.398333   19.184096  0.666667    0.333333 -224.618833
1            2   5304.975000    2.652489  0.000000    1.000000  -27.284523
2           11   5996.891818   16.491448  0.636364    0.000000  288.491337
3           10   6188.349000   15.470867  1.000000    0.000000  985.067745
4            8   8862.468750   17.724932  1.000000    0.000000  145.007350

   value classification sentiment_binary
0     72          Greed            Greed
1     70          Greed            Greed
2     73          Greed            Greed
3     73          Greed            Greed
4     74          Greed            Greed

In [155]:
print(daily.shape)
print(daily['sentiment_binary'].value_counts())
print(daily['net_pnl'].describe())

(1690, 12)
sentiment_binary
Greed      843
Fear       571
Neutral    276
Name: count, dtype: int64
count      1690.000000
mean       5960.031308
std       33083.910116
min     -346794.680932
25%         102.649529
50%         758.988003
75%        3147.324846
max      533757.033267
Name: net_pnl, dtype: float64

In [156]:
df_daily = daily.copy()

In [158]:
df_daily.shape

(1690, 12)

In [159]:
df_merged.shape

(104266, 12)

In [162]:
df_merged.to_csv('/Users/abhinandho/Desktop/Trader Behaviour & Performance Analytics/data/df_merged.csv',index = False)
df_daily.to_csv('/Users/abhinandho/Desktop/Trader Behaviour & Performance Analytics/data/df_daily.csv',index = False)

In [ ]:
# end of notebook data auditing & data preparation #